/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_ysdk_module_bugly_BuglyNativeListener */

#ifndef _Included_com_tencent_ysdk_module_bugly_BuglyNativeListener
#define _Included_com_tencent_ysdk_module_bugly_BuglyNativeListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_ysdk_module_bugly_BuglyNativeListener
 * Method:    OnCrashExtMessageNotify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_ysdk_module_bugly_BuglyNativeListener_OnCrashExtMessageNotify
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_ysdk_module_bugly_BuglyNativeListener
 * Method:    OnCrashExtDataNotify
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_ysdk_module_bugly_BuglyNativeListener_OnCrashExtDataNotify
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
