#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDKPackage.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SdkPackage")]
	public partial class GamesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertsdk_Games(sdk_Games instance);
    partial void Updatesdk_Games(sdk_Games instance);
    partial void Deletesdk_Games(sdk_Games instance);
    #endregion
		
		public GamesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SdkPackageConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GamesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GamesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GamesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GamesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sdk_Games> sdk_Games
		{
			get
			{
				return this.GetTable<sdk_Games>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sdk_Games")]
	public partial class sdk_Games : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GameName;
		
		private string _GameDisplayName;
		
		private int _GameStatus;
		
		private string _GamePic;
		
		private string _GameIntroduce;
		
		private string _GameWebSite;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGameNameChanging(string value);
    partial void OnGameNameChanged();
    partial void OnGameDisplayNameChanging(string value);
    partial void OnGameDisplayNameChanged();
    partial void OnGameStatusChanging(int value);
    partial void OnGameStatusChanged();
    partial void OnGamePicChanging(string value);
    partial void OnGamePicChanged();
    partial void OnGameIntroduceChanging(string value);
    partial void OnGameIntroduceChanged();
    partial void OnGameWebSiteChanging(string value);
    partial void OnGameWebSiteChanged();
    #endregion
		
		public sdk_Games()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GameName
		{
			get
			{
				return this._GameName;
			}
			set
			{
				if ((this._GameName != value))
				{
					this.OnGameNameChanging(value);
					this.SendPropertyChanging();
					this._GameName = value;
					this.SendPropertyChanged("GameName");
					this.OnGameNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameDisplayName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GameDisplayName
		{
			get
			{
				return this._GameDisplayName;
			}
			set
			{
				if ((this._GameDisplayName != value))
				{
					this.OnGameDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._GameDisplayName = value;
					this.SendPropertyChanged("GameDisplayName");
					this.OnGameDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameStatus", DbType="Int NOT NULL")]
		public int GameStatus
		{
			get
			{
				return this._GameStatus;
			}
			set
			{
				if ((this._GameStatus != value))
				{
					this.OnGameStatusChanging(value);
					this.SendPropertyChanging();
					this._GameStatus = value;
					this.SendPropertyChanged("GameStatus");
					this.OnGameStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GamePic", DbType="NVarChar(200)")]
		public string GamePic
		{
			get
			{
				return this._GamePic;
			}
			set
			{
				if ((this._GamePic != value))
				{
					this.OnGamePicChanging(value);
					this.SendPropertyChanging();
					this._GamePic = value;
					this.SendPropertyChanged("GamePic");
					this.OnGamePicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameIntroduce", DbType="NVarChar(1000)")]
		public string GameIntroduce
		{
			get
			{
				return this._GameIntroduce;
			}
			set
			{
				if ((this._GameIntroduce != value))
				{
					this.OnGameIntroduceChanging(value);
					this.SendPropertyChanging();
					this._GameIntroduce = value;
					this.SendPropertyChanged("GameIntroduce");
					this.OnGameIntroduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameWebSite", DbType="NVarChar(200)")]
		public string GameWebSite
		{
			get
			{
				return this._GameWebSite;
			}
			set
			{
				if ((this._GameWebSite != value))
				{
					this.OnGameWebSiteChanging(value);
					this.SendPropertyChanging();
					this._GameWebSite = value;
					this.SendPropertyChanged("GameWebSite");
					this.OnGameWebSiteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
