#ifndef __WDJ_SCREENSHOT_H__
#define __WDJ_SCREENSHOT_H__
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wandoujia_udid_UDIDUtil */

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_wandoujia_mariosdk_plugin_apk_utils_ScreenShotUtils_nativeScreenshotSupported(JNIEnv* , jclass);

JNIEXPORT jstring JNICALL Java_com_wandoujia_mariosdk_plugin_apk_utils_ScreenShotUtils_nativeTakeScreenshot(JNIEnv* , jclass);

#ifdef __cplusplus
}
#endif
#endif  // __WDJ_SCREENSHOT_H__
