/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_tmgp_yybtestsdk_PlatformTest */

#ifndef _Included_com_tencent_tmgp_yybtestsdk_PlatformTest
#define _Included_com_tencent_tmgp_yybtestsdk_PlatformTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    setActivity
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_setActivity
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getChannelId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getChannelId
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getRegisterChannelId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getRegisterChannelId
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    isPlatformInstalled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_isPlatformInstalled
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getPlatformAppVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getPlatformAppVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    login
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_login
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_logout
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getLoginRecord
 * Signature: (Lcom/tencent/ysdk/module/user/UserLoginRet;)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getLoginRecord
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getPf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getPf
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    getPfKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_getPfKey
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    switchUser
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_switchUser
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    queryUserInfo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_queryUserInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    reportEvent
 * Signature: (Ljava/lang/String;Ljava/util/HashMap;Z)V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_reportEvent
  (JNIEnv *, jclass, jstring, jobject, jboolean);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    recharge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z[BILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_recharge
  (JNIEnv *, jclass, jstring, jstring, jboolean, jbyteArray, jint, jstring);

/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    buyGoods
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_buyGoods
  (JNIEnv *, jclass, jstring, jstring, jbyteArray, jint, jstring);


/*
 * Class:     com_tencent_tmgp_yybtestsdk_PlatformTest
 * Method:    testNativeCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_tmgp_yybtestsdk_PlatformTest_testNativeCrash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
