/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_ysdk_module_user_UserNativeListener */

#ifndef _Included_com_tencent_ysdk_module_user_UserNativeListener
#define _Included_com_tencent_ysdk_module_user_UserNativeListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_ysdk_module_user_UserNativeListener
 * Method:    OnLoginNotify
 * Signature: (Lcom/tencent/ysdk/module/user/UserLoginRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_ysdk_module_user_UserNativeListener_OnLoginNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_ysdk_module_user_UserNativeListener
 * Method:    OnWakeupNotify
 * Signature: (Lcom/tencent/ysdk/module/user/WakeupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_ysdk_module_user_UserNativeListener_OnWakeupNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_ysdk_module_user_UserNativeListener
 * Method:    OnRelationNotify
 * Signature: (Lcom/tencent/ysdk/module/user/UserRelationRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_ysdk_module_user_UserNativeListener_OnRelationNotify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
