/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_ysdk_module_pay_PayNativeListener */

#ifndef _Included_com_tencent_ysdk_module_pay_PayNativeListener
#define _Included_com_tencent_ysdk_module_pay_PayNativeListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_ysdk_module_pay_PayNativeListener
 * Method:    OnPayNotify
 * Signature: (Lcom/tencent/ysdk/module/pay/PayRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_ysdk_module_pay_PayNativeListener_OnPayNotify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
